// Generated by CoffeeScript 1.12.5
(function() {
  var weightConv;

  weightConv = {
    button: document.getElementById('addButton'),
    childNameInput: document.getElementById('childName'),
    currentWeight: document.getElementById('weightInKg'),
    lbs: 453.592,
    oz: 28.3495,
    init: function() {
      weightConv.button.addEventListener('click', weightConv.calculateValues);
    },
    getChildName: function() {
      return document.getElementById('childName').value;
    },
    lbsFloor: function() {
      return Math.floor(weightConv.lbsTrunc());
    },
    lbsTrunc: function() {
      return Math.trunc(weightConv.kg2grams) / weightConv.lbs;
    },
    ouncesCalc: function() {
      return weightConv.kg2grams - (weightConv.lbsFloor() * weightConv.lbs);
    },
    ozFloored: function() {
      return Math.floor(weightConv.ouncesCalc()) / weightConv.oz;
    },
    ozTrunc: function() {
      return Math.trunc(weightConv.ozFloored());
    },
    getTodaysDate: function() {
      return (new moment).format('YYYY-MM-DD');
    },
    finalWeight: function() {
      return weightConv.lbsFloor() + 'lbs ' + weightConv.ozTrunc() + 'ozs';
    },
    calculateValues: function() {
      var error, jsonOutput, printDate, printOut;
      weightConv.currentWeight = weightConv.currentWeight.value;
      weightConv.kg2grams = weightConv.currentWeight * 1000;
      printOut = {
        date: weightConv.getTodaysDate(),
        child: weightConv.getChildName(),
        weight: weightConv.finalWeight()
      };
      if (weightConv.currentWeight > 0) {
        printDate = moment().format('dddd, MMMM Do, YYYY');
        document.getElementById('pResults').innerHTML = 'Todays date is ' + printDate + ' <br /> ' + printOut.child + ' is: ' + printOut.weight;
        weightConv.currentWeight.value = '';
        console.log(printOut);
      } else {
        error = document.getElementById('pResults').innerHTML = 'Did you mean to submit without a value?';
      }
      jsonOutput = JSON.stringify(printOut);
      return $.ajax({
        method: 'POST',
        url: 'send.php',
        data: jsonOutput,
        success: function(data) {
          return console.log(data);
        },
        error: function(jqXHR, error, errorThrown) {
          return console.log('Data not sent! ' + errorThrown + ' ' + jqXHR.responseText);
        }
      });
    }
  };

  weightConv.init();

}).call(this);
